# Generated by Django 4.2.2 on 2023-07-20 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'pending'), ('C', 'completed'), ('F', 'failed')], default='P', max_length=1)),
                ('payment_option', models.CharField(choices=[('P', 'paypal'), ('S', 'stripe')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=60, verbose_name='balance')),
                ('account_name', models.CharField(max_length=250, verbose_name='account name')),
                ('account_number', models.CharField(max_length=100, verbose_name='account number')),
                ('bank', models.CharField(max_length=100, verbose_name='bank')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('password', models.CharField(max_length=200, verbose_name='password')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=250, verbose_name='transaction id')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('fail', 'Fail')], default='pending', max_length=200, null=True)),
                ('transaction_type', models.CharField(choices=[('funding', 'Bank Transfer Funding'), ('payout', 'Bank Transfer Payout'), ('debit user wallet', 'Debit User Wallet'), ('credit user wallet', 'Credit User Wallet')], max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=60, verbose_name='amount')),
                ('date', models.CharField(max_length=200, verbose_name='date')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.wallet')),
            ],
        ),
    ]
