# Generated by Django 4.2.2 on 2023-08-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_category_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
