# Generated by Django 4.2.2 on 2023-08-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_category_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimg",
            name="productId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_imgs",
                to="commerce.product",
            ),
        ),
    ]
