# Generated by Django 4.2.2 on 2023-08-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0006_alter_productimg_productid"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimg",
            name="image",
            field=models.ImageField(default=0, upload_to="product_images"),
            preserve_default=False,
        ),
    ]
