# Generated by Django 4.2.2 on 2023-08-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0008_remove_productimg_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="kilogram",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
