# Generated by Django 4.2.2 on 2023-08-20 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0009_product_kilogram"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organic", models.IntegerField()),
                ("expiration", models.IntegerField()),
                ("review", models.CharField(max_length=200)),
                ("gram", models.IntegerField()),
                (
                    "productId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_details",
                        to="commerce.product",
                    ),
                ),
            ],
        ),
    ]
