# Generated by Django 4.2.2 on 2023-08-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0010_productdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product", name="stock", field=models.IntegerField(),
        ),
    ]
