# Generated by Django 4.2.2 on 2023-07-20 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('reference', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('type', models.CharField(blank=True, choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=15)),
                ('category', models.CharField(max_length=15)),
            ],
        ),
    ]
